### ISSUE TITLE
cocoapods 无法安装

### ISSUE THREAD

**Issue by tonlen** [ivoryxiong/IdCardOCR#1]
[!] Unable to add a source with url `https://shenzhen.wumii.net/git/Public/WMSpecsRepo.git` named `wumii-git-public-wmspecsrepo`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

$ pod repo add wumii-git-public-wmspecsrepo https://shenzhen.wumii.net/git/Public/WMSpecsRepo.git
[!] /usr/bin/git clone https://shenzhen.wumii.net/git/Public/WMSpecsRepo.git wumii-git-public-wmspecsrepo

Cloning into 'wumii-git-public-wmspecsrepo'...
fatal: unable to access 'https://shenzhen.wumii.net/git/Public/WMSpecsRepo.git/': Could not resolve host: shenzhen.wumii.net

**Comment by ivoryxiong** [comment]
updated , use last commit , card.io should build from https://github.com/ivoryxiong/card.io-iOS-source.git by yourself.

**Comment by tonlen** [comment]
thanks

**Comment by tonlen** [comment]
@ivoryxiong 识别出身份证号码以后，识别姓名出现allow_blob_division，没有任何奔溃信息，像直接exit()一样就闪退了，这是chi_idcard.traineddata的问题还是？？
